{{ $_ := set . "appName" "notary-wrapper-certs" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
type: Opaque
data:
  notary-wrapper.crt: {{ .Files.Get "certs/notary-wrapper.crt" | b64enc }}
  notary-wrapper.key: {{ .Files.Get "certs/notary-wrapper.key" | b64enc }}
